version: '3'
services:
  nginx:
    image: nginx:stable
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./conf/nginx/ssl:/etc/nginx/ssl
      - ./conf/nginx/server.nginx.conf:/etc/nginx/conf.d/server.nginx.conf
